# Generated by Django 4.2.6 on 2023-11-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0003_rename_dca_license_number_parkingspace_parking_spot_id_and_more"),
        ("users", "0002_user_avatar_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="parking_space",
            field=models.ForeignKey(
                default=59763,
                on_delete=django.db.models.deletion.CASCADE,
                to="map.parkingspace",
            ),
            preserve_default=False,
        ),
    ]
