# Generated by Django 4.2.6 on 2023-11-12 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_post_parking_space"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userverification",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AddField(
            model_name="userverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("in_progress", "In progress"),
                    ("cancelled", "Cancelled"),
                    ("verified", "Verified"),
                ],
                default="submitted",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="userverification",
            name="submitted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="userverification",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
