# Generated by Django 4.2.6 on 2023-12-06 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_userverification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
