# Generated by Django 4.2.6 on 2023-10-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dca_license_number", models.CharField(max_length=200)),
                ("address_zip", models.CharField(max_length=200)),
                ("longitude", models.CharField(max_length=200)),
                ("latitude", models.CharField(max_length=200)),
                ("business_name", models.CharField(max_length=200)),
            ],
        ),
    ]
