# Generated by Django 4.2.6 on 2023-11-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspace",
            name="id",
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="dca_license_number",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
