# Generated by Django 4.2.6 on 2023-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0003_rename_dca_license_number_parkingspace_parking_spot_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspace",
            name="occupancy_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
