# Generated by Django 4.2.6 on 2023-11-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0006_occupancyhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupancyhistory",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="occupancyhistory",
            name="parking_space",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occupancy_history",
                to="map.parkingspace",
            ),
        ),
    ]
