# Generated by Django 4.2.6 on 2023-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0007_occupancyhistory_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspace",
            name="vehicle_spaces_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
