# Generated by Django 4.2.6 on 2023-12-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0008_parkingspace_vehicle_spaces_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspace",
            name="available_vehicle_spaces",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
